language: android
android:
  components:
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    
    licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

branches:
  only:  
  - master
