language: android
android:
  components:
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    

before_install:
  - chmod +x gradlew

branches:
  only:  
  - master
